server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: docker-containers
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
        refresh_interval: 5s

    relabel_configs:
      - source_labels: [__meta_docker_container_name]
        regex: "/(loki|promtail|grafana)"
        action: drop

      - target_label: job
        replacement: docker

      - source_labels: [__meta_docker_container_name]
        regex: "/(.*)"
        target_label: container
        replacement: "$1"

      - source_labels: [ __meta_docker_container_name ]
        regex: "/subway-repo-*"
        target_label: app

      - source_labels: [ __meta_docker_container_id ]
        target_label: __path__
        replacement: /var/lib/docker/containers/$1/*-json.log

#scrape_configs:
#  - job_name: docker-containers
#    static_configs:
#      - targets: [localhost]
#        labels:
#          job: docker
#          service: subway-app
#          __path__: /var/lib/docker/containers/*/*-json.log
